run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gci
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mindfiredigital/DeepScanBot)

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/mindfiredigital/DeepScanBot

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
      - name: package-comments
        disabled: true
      - name: var-naming
      - name: indent-error-flow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gosec
        - gocyclo
        - noctx
