# This file was generated by GoReleaser. DO NOT EDIT.
cask "deepscanbot" do
  version "0.0.0-SNAPSHOT-9c379fa"

  on_macos do
    on_intel do
      sha256 "46ae0284f5a6a6d90014bf4f05ba2bd42ff2ca62a0e140632ac86382149f1c70"
      url "https://github.com/mindfiredigital/DeepScanBot/releases/download/v0.0.0/deepscanbot_darwin_amd64",
        verified: "github.com/mindfiredigital/DeepScanBot"
      binary "deepscanbot_darwin_amd64", target: "deepscanbot"
    end
    on_arm do
      sha256 "e96049af263a5bd243d1557dbea02f0bd1e13ef0f204d5b6554b69565121570d"
      url "https://github.com/mindfiredigital/DeepScanBot/releases/download/v0.0.0/deepscanbot_darwin_arm64",
        verified: "github.com/mindfiredigital/DeepScanBot"
      binary "deepscanbot_darwin_arm64", target: "deepscanbot"
    end
  end

  on_linux do
    on_intel do
      sha256 "034ba99fbd56e1c981c63bda84b8cd2fab8ff06c75eeb864f3670f8978e67864"
      url "https://github.com/mindfiredigital/DeepScanBot/releases/download/v0.0.0/deepscanbot_linux_amd64",
        verified: "github.com/mindfiredigital/DeepScanBot"
      binary "deepscanbot_linux_amd64", target: "deepscanbot"
    end
    on_arm do
      sha256 "9ee23d071fb7f42cfe94371f19c0364ff5074ef2ec89d6416fd57247c7d20fb7"
      url "https://github.com/mindfiredigital/DeepScanBot/releases/download/v0.0.0/deepscanbot_linux_arm64",
        verified: "github.com/mindfiredigital/DeepScanBot"
      binary "deepscanbot_linux_arm64", target: "deepscanbot"
    end
  end

  name "deepscanbot"
  desc "A high-performance web crawler and scanner - recursively crawls websites, respects robots.txt, handles rate-limiting, and produces comprehensive JSON or text reports"
  homepage "https://github.com/mindfiredigital/DeepScanBot"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "deepscanbot",
    ]

  depends_on formula: [
      "ca-certificates",
      "git",
    ]

  # No zap stanza required

end
